/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MmMediaGallery {
    }
}
declare global {
    interface HTMLMmMediaGalleryElement extends Components.MmMediaGallery, HTMLStencilElement {
    }
    var HTMLMmMediaGalleryElement: {
        prototype: HTMLMmMediaGalleryElement;
        new (): HTMLMmMediaGalleryElement;
    };
    interface HTMLElementTagNameMap {
        "mm-media-gallery": HTMLMmMediaGalleryElement;
    }
}
declare namespace LocalJSX {
    interface MmMediaGallery {
    }
    interface IntrinsicElements {
        "mm-media-gallery": MmMediaGallery;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mm-media-gallery": LocalJSX.MmMediaGallery & JSXBase.HTMLAttributes<HTMLMmMediaGalleryElement>;
        }
    }
}
